version: '3'
# Services means containers
services:
  redis-server:
    image: 'redis'
  node-app:
    # Restart policy
    restart: always # on-failure, "no", unless-stop 
    # Look into current directory for Dockerfile and build an image
    build: .
    # Specify ports we need opened
    ports:
      - "4001:8081"